Evidence ui-section of mi-details page
ELEVATE-Project/observation-survey-projects-pwa pull request #197
Opened 2024-12-02 11:43 UTC by codeNaveen1234

2024-12-02 12:18 UTC, Vinod-V3 commented on src/app/mi-details/mi-details.page.html
> +            @if(isFileType(item.title, 'image')){
wouldnt this make the page slower as this function gets called for each rendering

2024-12-03 04:11 UTC, 5Amogh requested changes

2024-12-03 04:11 UTC, 5Amogh commented on src/app/mi-details/mi-details.page.html
> +            @if(!item.isImage){
using else instead of re-using if for the inverse condition

2024-12-03 05:25 UTC, 5Amogh approved these changes

2024-12-03 05:27 UTC, merged